const words = [
    { en: "apple", zh: "苹果", pinyin: "píng guǒ" },
    { en: "ball", zh: "球", pinyin: "qiú" },
    { en: "cat", zh: "猫", pinyin: "māo" },
    { en: "dog", zh: "狗", pinyin: "gǒu" },
    { en: "elephant", zh: "大象", pinyin: "dà xiàng" },
    { en: "fish", zh: "鱼", pinyin: "yú" },
    { en: "grape", zh: "葡萄", pinyin: "pú táo" },
    { en: "hat", zh: "帽子", pinyin: "mào zi" },
    { en: "ice", zh: "冰", pinyin: "bīng" },
    { en: "juice", zh: "果汁", pinyin: "guǒ zhī" },
    { en: "kite", zh: "风筝", pinyin: "fēng zhēng" },
    { en: "lion", zh: "狮子", pinyin: "shī zi" },
    { en: "moon", zh: "月亮", pinyin: "yuè liàng" },
    { en: "nest", zh: "巢", pinyin: "cháo" },
    { en: "owl", zh: "猫头鹰", pinyin: "māo tóu yīng" },
    { en: "pig", zh: "猪", pinyin: "zhū" },
    { en: "quack", zh: "嘎嘎声", pinyin: "gā gā shēng" },
    { en: "rabbit", zh: "兔子", pinyin: "tù zi" },
    { en: "sun", zh: "太阳", pinyin: "tài yáng" },
    { en: "tree", zh: "树", pinyin: "shù" },
    { en: "umbrella", zh: "雨伞", pinyin: "yǔ sǎn" },
    { en: "violin", zh: "小提琴", pinyin: "xiǎo tí qín" },
    { en: "water", zh: "水", pinyin: "shuǐ" },
    { en: "xylophone", zh: "木琴", pinyin: "mù qín" },
    { en: "yarn", zh: "纱线", pinyin: "shā xiàn" },
    { en: "zebra", zh: "斑马", pinyin: "bān mǎ" },
    { en: "book", zh: "书", pinyin: "shū" },
    { en: "car", zh: "汽车", pinyin: "qì chē" },
    { en: "duck", zh: "鸭", pinyin: "yā" },
    { en: "flower", zh: "花", pinyin: "huā" },
];

const englishWords = words.map((word) => word.en);

console.log(englishWords);
